[build]
    base = "vue"
    command = "npm run build"
    publish = "dist"
    environment = { NODE_VERSION = "12" }
    functions = "./functions"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200